### ISSUE TITLE
ACF fields import support

### ISSUE THREAD

**Issue by njbarrett** [gathercontent/wordpress-plugin#21]
Hey there,

The plugin claims to support importing ACF fields.
How would one do this? As I notice in my post meta table there are always 2 post meta per acf field.
One prefixed with an underscore with the field name, e.g 

_article_content_2_image	field_584f67b5c7afb

And one with the actual value, e.g

article_content_2_image	1589

How would I go about making this work?

**Comment by jtsternberg** [comment]
You will select "Custom Fields" as the Mapped WordPress Field, and then add your ACF field id to the dropdown: ![](http://b.ustin.co/ujM6+)

You will use the actual value field ID, not the supporting one.

**Comment by jtsternberg** [comment]
Closing for now, but please let us know if you have any other issues.

**Comment by njbarrett** [comment]
@jtsternberg coming back to this one.

It seems the plugin does not create the supporting fields, therefore they are not mapped properly.

e.g created using the plugin:

![screen shot 2017-02-27 at 10 47 51 am](https://cloud.githubusercontent.com/assets/241407/23347062/677c3b30-fcda-11e6-80ab-00c3c1749031.png)

created normally:

![screen shot 2017-02-27 at 10 48 18 am](https://cloud.githubusercontent.com/assets/241407/23347065/6f1420a6-fcda-11e6-91fb-f04956bcede1.png)

**Comment by jtsternberg** [comment]
Can you provide screenshots of your ACF field setup, your GatherContent template setup, and your mapping setup?
