### ISSUE TITLE
Commit vendor dirs

### ISSUE THREAD

**Issue by inderpreet99** [gathercontent/wordpress-plugin#22]
It would be great if the vendor dirs (from `composer.json`) could be included within the plugin source. One can easily enough clone/install this plugin in their WordPress plugins folder, without needing to run composer on it.

**Comment by jtsternberg** [comment]
@inderpreet99 we don't actually use composer. The composer.json requirements are leftover from the plugin generator, and should be removed.

**Comment by jtsternberg** [comment]
Closing, but feel free to open another if you have any other questions.
