### ISSUE TITLE
Rejected cookie in admin-post.php

### ISSUE THREAD

**Issue by jdub233** [gathercontent/wordpress-plugin#27]
Hello,

The cookie impersonation setup for the admin-post.php request here:
https://github.com/gathercontent/wordpress-plugin/blob/2f77f1aee3ad13fe87cf6e65f3b3822da2f7ed4b/includes/classes/sync/async-base.php#L73

Doesn’t work with our login system.  Because the request comes from the server itself (instead of the admin user’s browser), our custom login logic rejects the cookie and won’t accept the request.

We would prefer not to punch a hole in our login system to accommodate a server-side process.  

It looks like the admin-post.php request is a part of the underlying wp-async library and is used to fork a new server side process, but would there be any way to modify the trigger so that it doesn’t rely on a fully authenticated cookie?  

Or can you suggest any other workaround?  Relying on impersonating an admin cookie is problematic in our setup.

**Comment by jtsternberg** [comment]
Fixed with 3.1.0. You should see the available update in your WordPress dashboard.
