### ISSUE TITLE
PHP Notices for GatherContent::$settings in Configure Selected Pages

### ISSUE THREAD

**Issue by wkw** [gathercontent/wordpress-plugin#3]
With `define('WP_DEBUG', true);` on 
PHP 5.6.7, GC-Import Version: 2.6.34

I'm getting repeated Notices of the form below for every selected object I'm importing, when using the *Configure Selected Pages* screen. 

**Notice:** Undefined property: GatherContent::$settings in /srv/www/pegcc.org/current/web/app/plugins/gathercontent-import/curl.php on line [681](https://github.com/gathercontent/wordpress-plugin/blob/master/curl.php#L681)

I was going to submit the modification below as PR (checking whether `$this->settings` is set) then decided there might be some larger concern and thought it better to run this by you.

Doesn't seem to be causing problems that I'm aware of, and I've done a few imports already. But we always run with debug on during development, and it generates a lot of warnings (er, Notice messages).

```
if ( isset($this->settings) &&
  isset( $cur_settings[$this->settings['project_id']] ) &&
	isset( $cur_settings[$this->settings['project_id']][$parent_id] ) ) {
	$new_parent_id = $cur_settings[$this->settings['project_id']][$parent_id]['overwrite'];
}
```

**Comment by Cyapow** [comment]
Updated the release and changed to use project_id from get_options. Have also updated wp.org
