### ISSUE TITLE
Paragraph tags in ACF Fields import

### ISSUE THREAD

**Issue by wkw** [gathercontent/wordpress-plugin#4]
Mat (or other):
Noticing I'm getting `<p>` tags around the custom ACF imported fields. See skitch image.
Is there a logical reason for that? or a setting at GC or in plugin where I can change the behavior?

Rather than cleansing the database on each import, I'm just resorting to running those custom fields through `strip_tags`, but it's going to be a little confusing to editors when they begin working in the CMS admin to see html tags where they shouldn't be.

I inspected the popup menu, and thankfully it dose not appear to have the wrapping in the html source.

![gc_acf_paragraph_tags](https://cloud.githubusercontent.com/assets/1691220/7967521/86093c82-09f8-11e5-82f6-d4c96aedbede.png)

**Comment by Cyapow** [comment]
Hi Wayne

You could possibly set them as plain text fields within GC before importing them. But as they already have HTML in you would have to go and remove the <p> tags throughout for these fields. 

If you set them as plain text you could then modify curl.php to strip_tags when the field is plain.

Thanks

Mat
