### ISSUE TITLE
Repeatable Fields are imported as a string concatenated together

### ISSUE THREAD

**Issue by acketon** [gathercontent/wordpress-plugin#45]
Repeatable Fields in GatherContent appear to be imported as a concatenated string all together and in a way that a user cannot detangle it in WordPress even if it is mapped to the `post content` area. 

Is there a way to at least separate these during a sync? Even separated by a new line would be helpful. Ideally I'd like to be able to import them as an array of values in a post meta field.

**Comment by HughbertD** [comment]
Hi @acketon 

Sorry for the delayed reply, our WordPress partners are actively working on support for repeatable fields from within GatherContent to WordPress. 

These will be mapped to [Advanced Custom Fields](https://www.advancedcustomfields.com) within WordPress, allowing you to have repeating, singular fields within WP as you do inside GatherContent. 

We are expecting the release of this functionality within the next month or two. 

Thanks for your patience
Hugh

**Comment by HughbertD** [comment]
Hi @acketon 

Just to follow up that as of version [3.2.4](https://github.com/gathercontent/wordpress-plugin/releases/tag/3.2.4) we now have repeatable field support via the custom fields within WordPress. 

This is slightly different to my previous comment, in that it isn't Advanced Custom Fields that we are mapping to, but rather the core functionality.
