### ISSUE TITLE
Errors in Template Mapping Screen When Yoast SEO Plugin Installed

### ISSUE THREAD

**Issue by mccicorp** [gathercontent/wordpress-plugin#50]
We have installed version 3.2.1 in a fresh install of WordPress 5.9, default 2022 theme. After installing the Yoast SEO plugin, when we view the template mapping screen, a number of errors are showing up. No other plugins are installed. 

Warning: array_merge(): Expected parameter 2 to be an array, null given in LOCAL-DIRECTORY/wp-content/plugins/gathercontent-import/includes/classes/admin/mapping/field-types/wpseo.php on line 85

Warning: array_diff(): Expected parameter 2 to be an array, null given in LOCAL-DIRECTORY/wp-content/plugins/gathercontent-import/includes/classes/admin/mapping/field-types/wpseo.php on line 88

Warning: array_diff(): Expected parameter 2 to be an array, null given in LOCAL-DIRECTORY/wp-content/plugins/gathercontent-import/includes/classes/admin/mapping/field-types/wpseo.php on line 88

If we then try to map a GatherContent field to an SEO field in WordPress. The select box for the field name is empty and we get the following error:

Warning: Invalid argument supplied for foreach() in LOCAL-DIRECTORY/wp-content/plugins/gathercontent-import/includes/classes/admin/mapping/field-types/base.php on line 78

**Comment by HughbertD** [comment]
Hi @mccicorp 

This should be fixed in version `3.2.6` released yesterday.
